# Generated by Django 4.2.9 on 2024-02-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment_text",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user_name",
        ),
        migrations.AddField(
            model_name="article",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="article_comments", to="blog.comment"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="topic",
            field=models.CharField(max_length=100),
        ),
    ]
